-- SynapseChain Database Schema

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Data table: stores uploaded data references
CREATE TABLE data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type VARCHAR(20) NOT NULL CHECK (type IN ('event', 'content')),
    raw_data_url TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    uploaded_by VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'received' CHECK (status IN ('received', 'processing', 'labeled', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- AI Labels: labels generated by the AI engine
CREATE TABLE ai_labels (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    data_id UUID NOT NULL REFERENCES data(id) ON DELETE CASCADE,
    labels JSONB NOT NULL DEFAULT '{}',
    confidence NUMERIC(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    model_version VARCHAR(50),
    processing_time_ms INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(data_id)
);

-- Human Labels: labels from human validators
CREATE TABLE human_labels (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    data_id UUID NOT NULL REFERENCES data(id) ON DELETE CASCADE,
    labels JSONB NOT NULL DEFAULT '{}',
    confidence NUMERIC(4,3) CHECK (confidence >= 0 AND confidence <= 1),
    validator_id VARCHAR(255) NOT NULL,
    action VARCHAR(10) NOT NULL CHECK (action IN ('accept', 'modify', 'reject')),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Final Labels: consensus output
CREATE TABLE final_labels (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    data_id UUID NOT NULL REFERENCES data(id) ON DELETE CASCADE,
    final_labels JSONB NOT NULL DEFAULT '{}',
    confidence NUMERIC(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    sources TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(data_id)
);

-- Validators: registered human validators
CREATE TABLE validators (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    reputation_score NUMERIC(4,3) DEFAULT 0.5,
    total_validations INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- API Keys: for data consumers
CREATE TABLE api_keys (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    key_hash VARCHAR(255) NOT NULL UNIQUE,
    owner VARCHAR(255) NOT NULL,
    permissions TEXT[] DEFAULT '{"read"}',
    rate_limit INTEGER DEFAULT 1000,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Usage Tracking: monetization hook
CREATE TABLE usage_tracking (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    api_key_id UUID REFERENCES api_keys(id),
    endpoint VARCHAR(255) NOT NULL,
    data_id UUID REFERENCES data(id),
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_data_status ON data(status);
CREATE INDEX idx_data_type ON data(type);
CREATE INDEX idx_ai_labels_data_id ON ai_labels(data_id);
CREATE INDEX idx_human_labels_data_id ON human_labels(data_id);
CREATE INDEX idx_human_labels_validator ON human_labels(validator_id);
CREATE INDEX idx_final_labels_data_id ON final_labels(data_id);
CREATE INDEX idx_usage_tracking_timestamp ON usage_tracking(timestamp);
CREATE INDEX idx_usage_tracking_api_key ON usage_tracking(api_key_id);
